### ISSUE TITLE
Bug found in --python-kinds option while generating a tag file

### ISSUE THREAD

**Issue by yevhen-m** [universal-ctags/universal-ctags.github.io#13]
Hey, I use ctags to generate tag files for python code.
I get an error, if I use --python-kinds=cf option
f stands for 'function' and is a valid python kind

here is a screenshot
![screenshot from 2015-10-28 18 30 45](https://cloud.githubusercontent.com/assets/10185058/10815484/0f795244-7e35-11e5-8fd5-85def6062c88.png)

Will be grateful, if you fix this issue ))

**Comment by masatake** [comment]
@yevhen-m, thank you for reporting. However, this is place for reporting an issue about u-ctags web site.
Please, visit https://github.com/universal-ctags/ctags/issues

**Comment by vhda** [comment]
This issue was moved to universal-ctags/ctags#648

**Comment by masatake** [comment]
@vhda, thank you.
