### ISSUE TITLE
domain and/or cert expiration

### ISSUE THREAD

**Issue by masatake** [universal-ctags/universal-ctags.github.io#28]
@cweagans 

When I logined to https://readthedocs.org/dashboard/ctags/domains/, I saw a message:

> "The configuration of your custom domain docs.ctags.io is pending. Go to the [domain page](https://readthedocs.org/dashboard/ctags/domains/3420/edit/) and follow the instructions to complete it."

and

https://readthedocs.org/dashboard/ctags/domains/3420/edit/ showed:

> SSL certificate status: Domain validation failed for docs.ctags.io 

Do you have any idea about these messages?

**Comment by cweagans** [comment]
It looks like readthedocs is having a hard time getting a cert for docs.ctags.io. It's possible that because RTD itself uses cloudflare, it's trying to proxy through cloudflare twice, which i imagine would cause some weird behaviors.

to test this, I turned off cloudflare proxying (so docs.ctags.io points directly at RTD). Once DNS propagates, I'll see if RTD stops complaining :)

**Comment by masatake** [comment]
@hirooih I forgot to refer to your name in this issue.

**Comment by hirooih** [comment]
> @hirooih I forgot to refer to your name in this issue.

Thank you.

I ask the RTD support for help.

Here is the answer.

> What should I do " to remove the "orange cloud" from your CNAME record (set it to "DNS only")".
> 
> You need to:
> 
> Log in your Cloudflare account (https://www.cloudflare.com/)
> Select your domain
> Click on "DNS"
> Find the CNAME record and click on "Edit"
> And uncheck the "Proxy status" option.

Does anyone have an account of Cloudflare?

**Comment by cweagans** [comment]
I have updated the configuration in Cloudflare:

![CleanShot 2022-10-26 at 11 05 56](https://user-images.githubusercontent.com/101590/198091000-13c8e46a-5999-4e14-b3d3-d35df07ab96b.png)

**Comment by cweagans** [comment]
(for clarity, I pay for ctags.io + have the domain set up on my cloudflare account. Feel free to @ me directly whenever you need changes made)

**Comment by masatake** [comment]
> (for clarity, I pay for ctags.io + have the domain set up on my cloudflare account. Feel free to @ me directly whenever you need changes made)

I didn't know that. Thank you very much.
I will pay for it. I would like to take over it. What I should do?

**Comment by cweagans** [comment]
If you'd like to take it over, the easiest way would be to get a namecheap account and let me know what your username is. I can transfer the domain to you that way. You'd also need to set up a cloudflare account if you don't already have one and set up ctags.io, copy the DNS records over, and then change the nameservers on the domain to point to whatever cloudflare specifies for you.

However, I don't mind continuing to pay for the domain registration and keep things online. Call it a project sponsorship 🙂  (It's like $35/year - really not a big deal)

**Comment by masatake** [comment]
@cweagans Sorry to be late. Have you paid the "$35/year" to Namecheap or Cloudflare?

**Comment by cweagans** [comment]
No worries! $35/yr is paid to Namecheap for the domain registration. Cloudflare is free.

**Comment by leleliu008** [comment]
I can not visit https://ctags.io/

![Screenshot from 2022-11-10 08-01-29](https://user-images.githubusercontent.com/3040852/200967844-eab2393e-fc3d-4737-8fbe-a0668afbde9f.png)
![Screenshot from 2022-11-10 08-03-20](https://user-images.githubusercontent.com/3040852/200968060-b5fd43dd-6d1c-4308-9787-5e4c98423890.png)

**Comment by cweagans** [comment]
Just made a couple of tweaks in the Cloudflare UI to hopefully get this resolved.

**Comment by masatake** [comment]
@cweagans Thank you very much. If I take over the account and payment, I doubt I can fix this https trouble like you. About this project, I would like to focus on improving ctags itself and explore the world of code reading and tools for it.

So I want you to have the account and the maintainership of https://ctags.io.
I have talked and written "See https://ctags.io" in so many places because there is you, the experienced site maintainer in this project.

As I wrote I didn't know about the payment. Thank you very much.
Instead of taking over the account and payment directly, I will represent my gratitude in a different way. You will know what I mean.

**Comment by masatake** [comment]
I logged in to https://readthedocs.org/dashboard/ctags/domains/ and I confirmed the issue is gone. 

@hirooih I'm sorry for your time on this issue. I think the issue is now fixed.

**Comment by hirooih** [comment]
> I think the issue is now fixed.

Thank you.  I'm sorry that I could not solve anything.

@cweagans,

Thank you for your help.

@leleliu008

Thank you for your reporting the issue.

@masatake

Thank you for your continued commitment to  this project.
