### ISSUE TITLE
[RFC] Running ctags on ctags source code and publish it on web

### ISSUE THREAD

**Issue by masatake** [universal-ctags/universal-ctags.github.io#9]
I found universal ctags project has people who knows well about web technology!

I'm interested in prepareing something following badge. 

![tagged](https://cloud.githubusercontent.com/assets/77077/8077577/dfdf6274-0f91-11e5-9dda-04d158ee00d0.png)

How do you think about this?

Preparing to the other projects is ideal. But as staring I would like to prepare it just for our code.
With pygments and ctags we can create hypertexted source code tree like

http://people.redhat.com/yamato/tmp/open-iscsi-2.0-872-rc4-bnx2i/libiscsi/libiscsi.c.html

How can we prepare such web site for our code, u-ctags itself?
The web site must be updated automatically when new commits are added to the git repo.

opengrok, GNU highlight and GNU global can be used, too.

**Comment by cweagans** [comment]
I think that's going to be a pretty involved project :) Let's revisit this in a month or so. By then, I'll have a server we can use to do this in a nicer way than Github Pages will allow us to.

**Comment by masatake** [comment]
The patch is merged. It is very small step for the goal.

**Comment by masatake** [comment]
http://pygments.simplabs.com/ handles requests for highlighting via web.
How about handling requests for tagging via web? Just an idea.

**Comment by masatake** [comment]
I made a mock demonstrating what I want. http://a.srpmix.org/ctags/names/main.html

**Comment by masatake** [comment]
We don't have enough capacity to do this item.
